import Provider from '@/context/provider';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DammySoft Blog | Next.js + TypeScript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 

  return (
    <html lang="en" className="h-full bg-white">
      <Provider>
      <body suppressHydrationWarning={true}
      className={`${inter.className} bg-slate-300 text-slate-1200 container mx-auto p-4 h-full`}>
        {children}
        </body>
      </Provider>
    </html>
  )
}
